apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: seyeonni/backend:latest
          ports:
            - containerPort: 8080
